plugins {
	id "fabric-loom" version "${loom_version}"
}

version = "fabric-${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

def configuredModVersion = mod_version
def configuredMinecraftVersion = minecraft_version
def configuredMinecraftDependency = minecraft_dependency
def configuredArchiveName = archives_base_name

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }
	maven { url = "https://maven.terraformersmc.com/" }
	maven { url = "https://maven.parchmentmc.org/" }
	maven { url = "https://repo.redlance.org/public" }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered() {
		officialMojangMappings()
		if(!project.parchment_version.isEmpty()) {
			parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
		}
	}
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation fabricApi.module("fabric-networking-api-v1", project.fabric_version)
	modImplementation fabricApi.module("fabric-key-binding-api-v1", project.fabric_version)
	modImplementation fabricApi.module("fabric-lifecycle-events-v1", project.fabric_version)
	modImplementation fabricApi.module("fabric-command-api-v2", project.fabric_version)
	modImplementation fabricApi.module("fabric-rendering-v1", project.fabric_version)
	modImplementation fabricApi.module("fabric-resource-loader-v1", project.fabric_version)
	modRuntimeOnly fabricApi.module("fabric-registry-sync-v0", project.fabric_version)

	// Allow logging into an actual Minecraft account in a dev env
	// See https://github.com/DJtheRedstoner/DevAuth
	modLocalRuntime "me.djtheredstoner:DevAuth-fabric:1.2.1"
	// TODO mojang removed their dependency on Apache HTTP, which breaks DevAuth; for the time being, just re-import it
	//      as a dev env dependency.
	localRuntime "org.apache.httpcomponents:httpclient:4.5.14"
	localRuntime "org.apache.httpcomponents:httpcore:4.4.16"

	// If you want to load Mod Menu in a development environment, change this to modImplementation
	// and uncomment the associated Fabric API module.
	modCompileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
	modCompileOnly("com.zigythebird.playeranim:PlayerAnimationLibFabric:${project.pal_version}")
	//modRuntimeOnly(fabricApi.module("fabric-screen-api-v1", project.fabric_version))
}

processResources {
	inputs.property "version", configuredModVersion
	inputs.property "minecraft_version", configuredMinecraftVersion
	inputs.property "minecraft_dependency", configuredMinecraftDependency

	filesMatching("fabric.mod.json") {
		expand "version": configuredModVersion,
				"minecraft_version": configuredMinecraftVersion,
				"minecraft_dependency": configuredMinecraftDependency
	}
}

tasks.withType(JavaCompile).configureEach {
	// Minecraft 1.20.5 (24w14a) upwards uses Java 21.
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

loom {
	decompilers {
		named("vineflower") {
			options.put("mark-corresponding-synthetics", "1")
		}
	}

	accessWidenerPath = file("src/main/resources/wildfire_gender.accesswidener")
}

jar {
	from("LICENSE") {
		rename { "${it}_${configuredArchiveName}" }
	}
}
