name: Feature Request
description: Suggest an improvement for FemaleGenderModExtended.
labels: ["Suggestion"]
body:
  - type: textarea
    id: describe-it
    attributes:
      label: "Describe the feature you're requesting"
    validations:
      required: true

  - type: checkboxes
    id: no-existing-request
    attributes:
      label: "This is not an existing request"
      description: Search existing issues before submitting a new request.
      options:
        - label: I searched existing issues and did not find this request.
          required: true
